### ISSUE TITLE
@types/react-native mobile 패키지 적용

### ISSUE THREAD

**Issue by yevi04** [poosoap/poosoap-frontend#13]
visual studio code에서 tsx파일에서 RN 기본 제공 컴포넌트들이 자동완성이 안되어서 이 부분 도입을 해봐야할것 같습니다.

**Comment by peanut-lover** [comment]
네 아마 NX를 root로 환경을 설정할 경우, 그렇더라구요. 그 부분은 찾아볼게요.

**Comment by yevi04** [comment]
아 해결되었습니다

**Comment by peanut-lover** [comment]
어떻게 해결됐나요? 구체적으로 알려주실 수 있을까요?

**Comment by yevi04** [comment]
넵!!

**Comment by yevi04** [comment]
제가 착가했습니다..
기존에 노가다로 'react-native' 부분을 추가해서 그랬습니다...

**Comment by yevi04** [comment]
넵 감사합니다

**Comment by peanut-lover** [comment]
> 기존에 노가다로 'react-native' 부분을 추가해서 그랬습니다...

이 부분 나중에 디코로 소통해보죠. ㅎㅎ 어떤 부분을 실수 하셨는지 궁금했어요.
